apiVersion: v1
kind: Secret
metadata:
  name: {{ include "atom_ctx.fullname" . }}-config
  labels:
    {{- include "atom_ctx.labels" . | nindent 4 }}
type: Opaque
stringData:
  ctx.conf: |
{{ toJson .Values.ctx.config | indent 4 }}
