apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "atom_ctx.fullname" . }}-config
  labels:
    {{- include "atom_ctx.labels" . | nindent 4 }}
data:
  ctx.conf: |
    {{- .Values.config | toPrettyJson | nindent 4 }}
